#python defading-diffusion-pytorch/cifar10_train.py --time_steps 50 --save_folder ./cifar_inpainting --discrete --sampling_routine x0_step_down --train_steps 700000 --blur_std 0.1 --fade_routine Random_Incremental

#python defading-diffusion-pytorch/celebA_train.py --time_steps 50 --save_folder ./celebA_inpainting --discrete --sampling_routine x0_step_down --train_steps 700000 --blur_std 0.1 --fade_routine Random_Incremental

#python defading-diffusion-pytorch/mnist_train.py --time_steps 50 --save_folder ./mnist_inpainting --discrete --sampling_routine x0_step_down --train_steps 700000 --blur_std 0.1 --fade_routine Random_Incremental

#python defading-diffusion-pytorch/celebA_train.py --time_steps 200 --save_folder ./celebA_128_200_step --discrete --sampling_routine x0_step_down --train_steps 350000 --kernel_std 0.1 --fade_routine Random_Incremental --initial_mask 1 --image_size 128 --load_path /cmlscratch/eborgnia/cold_diffusion/celebA_128_200_step/model.pt
#python defading-diffusion-pytorch/celebA_train.py --time_steps 100 --save_folder ./celebA_128_100_step --discrete --sampling_routine x0_step_down --train_steps 350000 --kernel_std 0.2 --fade_routine Random_Incremental --initial_mask 1 --image_size 128 --load_path /cmlscratch/eborgnia/cold_diffusion/celebA_128_100_step/model.pt
#python defading-diffusion-pytorch/celebA_train.py --time_steps 50 --save_folder ./celebA_128_50_step --discrete --sampling_routine x0_step_down --train_steps 350000 --kernel_std 0.4 --fade_routine Random_Incremental --initial_mask 1 --image_size 128 --load_path /cmlscratch/eborgnia/cold_diffusion/celebA_128_50_step/model.pt
#python defading-diffusion-pytorch/celebA_train.py --time_steps 100 --save_folder ./celebA_128_100_step_data_augmentation --discrete --sampling_routine x0_step_down --train_steps 350000 --kernel_std 0.2 --fade_routine Random_Incremental --initial_mask 11 --image_size 128 --dataset celebA --load_path /cmlscratch/eborgnia/cold_diffusion/celebA_128_100_step_data_augmentation/model.pt

#python defading-diffusion-pytorch/celebA_train.py --time_steps 200 --save_folder ./celebA_128_200_step_float --sampling_routine x0_step_down --train_steps 350000 --kernel_std 0.1 --fade_routine Random_Incremental --initial_mask 1 --image_size 128 --load_path /cmlscratch/eborgnia/cold_diffusion/celebA_128_200_step_float/model.pt
#python defading-diffusion-pytorch/celebA_train.py --time_steps 100 --save_folder ./celebA_128_100_step_float --sampling_routine x0_step_down --train_steps 350000 --kernel_std 0.2 --fade_routine Random_Incremental --initial_mask 1 --image_size 128 --load_path /cmlscratch/eborgnia/cold_diffusion/celebA_128_100_step_float/model.pt
#python defading-diffusion-pytorch/celebA_train.py --time_steps 50 --save_folder ./celebA_128_50_step_float --sampling_routine x0_step_down --train_steps 350000 --kernel_std 0.4 --fade_routine Random_Incremental --initial_mask 1 --image_size 128 --load_path /cmlscratch/eborgnia/cold_diffusion/celebA_128_50_step_float/model.pt
#python defading-diffusion-pytorch/celebA_train.py --time_steps 100 --save_folder ./celebA_128_100_step_data_augmentation_float --sampling_routine x0_step_down --train_steps 350000 --kernel_std 0.2 --fade_routine Random_Incremental --initial_mask 11 --image_size 128 --dataset celebA --load_path /cmlscratch/eborgnia/cold_diffusion/celebA_128_100_step_data_augmentation_float/model.pt

#python defading-diffusion-pytorch/celebA_train.py --time_steps 200 --fade_routine Incremental --save_folder ./centered_mask_celebA_128_200_step_ker_0.2_float --sampling_routine x0_step_down --train_steps 350000 --kernel_std 0.2 --initial_mask 1 --image_size 128
#python defading-diffusion-pytorch/celebA_train.py --time_steps 100 --fade_routine Incremental --save_folder ./centered_mask_celebA_128_100_step_ker_0.2_float --sampling_routine x0_step_down --train_steps 350000 --kernel_std 0.2 --initial_mask 1 --image_size 128
#python defading-diffusion-pytorch/celebA_train.py --time_steps 50 --fade_routine Incremental --save_folder ./centered_mask_celebA_128_50_step_ker_0.2_float --sampling_routine x0_step_down --train_steps 350000 --kernel_std 0.2 --initial_mask 1 --image_size 128
#python defading-diffusion-pytorch/celebA_train.py --time_steps 100 --fade_routine Incremental --save_folder ./centered_mask_celebA_128_100_step_ker_0.2_data_augmentation_float --sampling_routine x0_step_down --train_steps 350000 --kernel_std 0.2 --initial_mask 1 --image_size 128 --dataset celebA
#python defading-diffusion-pytorch/celebA_train.py --time_steps 125 --fade_routine Incremental --save_folder ./centered_mask_celebA_128_125_step_ker_0.2_float --sampling_routine x0_step_down --train_steps 350000 --kernel_std 0.2 --initial_mask 1 --image_size 128
#python defading-diffusion-pytorch/celebA_train.py --time_steps 150 --fade_routine Incremental --save_folder ./centered_mask_celebA_128_150_step_ker_0.2_float --sampling_routine x0_step_down --train_steps 350000 --kernel_std 0.2 --initial_mask 1 --image_size 128
#python defading-diffusion-pytorch/celebA_train.py --time_steps 100 --fade_routine Incremental --save_folder ./centered_mask_celebA_128_100_step_ker_0.2_data_augmentation --discrete --sampling_routine x0_step_down --train_steps 350000 --kernel_std 0.2 --initial_mask 1 --image_size 128 --dataset celebA

python defading-diffusion-pytorch/celebA_train.py --time_steps 100 --fade_routine Incremental --save_folder ./centered_mask_celebA_128_100_step_ker_0.2_float --sampling_routine x0_step_down --train_steps 350000 --kernel_std 0.2 --initial_mask 1 --image_size 128 --load_path /cmlscratch/eborgnia/cold_diffusion/centered_mask_celebA_128_100_step_ker_0.2_float/model.pt
python defading-diffusion-pytorch/celebA_train.py --time_steps 50 --fade_routine Incremental --save_folder ./centered_mask_celebA_128_50_step_ker_0.2_float --sampling_routine x0_step_down --train_steps 350000 --kernel_std 0.2 --initial_mask 1 --image_size 128 --load_path /cmlscratch/eborgnia/cold_diffusion/centered_mask_celebA_128_50_step_ker_0.2_float/model.pt
python defading-diffusion-pytorch/celebA_train.py --time_steps 100 --fade_routine Incremental --save_folder ./centered_mask_celebA_128_100_step_ker_0.2_data_augmentation_float --sampling_routine x0_step_down --train_steps 350000 --kernel_std 0.2 --initial_mask 1 --image_size 128 --dataset celebA --load_path /cmlscratch/eborgnia/cold_diffusion/centered_mask_celebA_128_100_step_ker_0.2_data_augmentation_float/model.pt